// <auto-generated />
namespace _0702.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class DisplayInfoForAllRole : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DisplayInfoForAllRole));
        
        string IMigrationMetadata.Id
        {
            get { return "202010071742521_DisplayInfoForAllRole"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
